# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install system build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the project files
COPY . /app

# Install pip dependencies using pip
RUN pip install --upgrade pip && pip install .

# Command to run the MCP server
CMD ["python", "main.py"]